// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuN1ZaGKn3HaUK9F6EY2lUnQfUIJqKhwo',
    appId: '1:94676098605:web:0847aca8921cafd6a562a4',
    messagingSenderId: '94676098605',
    projectId: 'patelproperties-8db21',
    authDomain: 'patelproperties-8db21.firebaseapp.com',
    storageBucket: 'patelproperties-8db21.firebasestorage.app',
    measurementId: 'G-H662KCN3Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOVrjrokFPH7-y44jms6rpibvpvTNNHO8',
    appId: '1:94676098605:android:e8f6e43cecbd04cba562a4',
    messagingSenderId: '94676098605',
    projectId: 'patelproperties-8db21',
    storageBucket: 'patelproperties-8db21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc_JYLSFWXvBE-Lw9UiDorxIg4-gK1q9U',
    appId: '1:94676098605:ios:66e4e68261378451a562a4',
    messagingSenderId: '94676098605',
    projectId: 'patelproperties-8db21',
    storageBucket: 'patelproperties-8db21.firebasestorage.app',
    iosBundleId: 'com.example.patelProperties',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc_JYLSFWXvBE-Lw9UiDorxIg4-gK1q9U',
    appId: '1:94676098605:ios:66e4e68261378451a562a4',
    messagingSenderId: '94676098605',
    projectId: 'patelproperties-8db21',
    storageBucket: 'patelproperties-8db21.firebasestorage.app',
    iosBundleId: 'com.example.patelProperties',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuN1ZaGKn3HaUK9F6EY2lUnQfUIJqKhwo',
    appId: '1:94676098605:web:eef2f419a0c6793ba562a4',
    messagingSenderId: '94676098605',
    projectId: 'patelproperties-8db21',
    authDomain: 'patelproperties-8db21.firebaseapp.com',
    storageBucket: 'patelproperties-8db21.firebasestorage.app',
    measurementId: 'G-E38G6FYTP7',
  );
}
